### ISSUE TITLE
Issue with OTA upgrades after applying OTA: platform:esphome to config

### ISSUE THREAD

**Issue by azoner2965** [ApolloAutomation/MSR-1#41] opened 2024-06-20 14:39 UTC
I added the required 
ota:
  - platform: esphome
to all of my device's config  and now they all work except for the MSR1. It compiles but will not upload with the following error:
ERROR ESP requests password, but no password given!

**Comment by bluecobras09** [comment] 2024-06-20 14:41
Add the password line also with the password from the MSR-1 yaml under 
the platform.


------ Original Message ------
From "azoner2965" ***@***.***>
To "ApolloAutomation/MSR-1" ***@***.***>
Cc "Subscribed" ***@***.***>
Date 6/20/2024 10:39:44 AM
Subject [ApolloAutomation/MSR-1] Issue with OTA upgrades after applying 
OTA: platform:esphome to config (Issue #41)

**Comment by azoner2965** [comment] 2024-06-20 14:45
Where do I retrieve the password from?

**Comment by bharvey88** [comment] 2024-06-20 16:16
this is a duplicate of #40

> I added the required ota:
> 
>     * platform: esphome
>       to all of my device's config  and now they all work except for the MSR1. It compiles but will not upload with the following error:
>       ERROR ESP requests password, but no password given!

There were two breaking changes to esphome and we're in the process of getting the yaml updated on the github repos for each device so that your updates will succeed. For now the easy answer is to not upgrade and wait for us to update our end. Once that's done, you should be able to validate and then install in esphome dashboard and the upgrade should then succeed. There are no benefits to upgrading to 2024.6.1 at this time.

**Comment by TrevorSchirmer** [comment] 2024-06-20 16:34
@azoner2965 Correction has been merged. It might take 24 hours for your ESPHome to clear the cache and see the update. Thanks!

**Closed by TrevorSchirmer** 2024-06-20 16:34 UTC

**Comment by azoner2965** [comment] 2024-06-20 20:14
Wow, that was fast! Thank you.
